### ISSUE TITLE
Review, General

### ISSUE THREAD

**Issue by vr8hub** [villeporte/arthur-machen_the-three-impostors#1]
- [x] Semanticate makes a change on the M.D. abbreviation in chapter 7 that should be accepted.
- [x] Modernize spelling points out the differences between commonsense (adjective) and common sense (noun). Chapter 4 contains a noun sense that is formatted as an adjective.
- [x] The filenames and ID's are off because of the prologue. The prologue should have a filename/id of prologue, and then the chapters should be named/numbered according to their actual number. Thus, "Adventure of the Gold Tiberius" is chapter 1, and so forth.
- [x] The short description is a little long, and the long description is a little short. :) The short description doesn't need "The novel follows…" as prefix, just something like "Two idlers in Victorian London get caught up in the search for a rare Roman coin." or something similar. The second paragraph of the long description doesn't tell us what the novel is about. We don't want spoilers, but we do want to know what it's about, which helps inform why we would want to read it.

**Comment by villeporte** [comment]
I've fixed the spelling of common sense. I haven't marked it as editorial since the correct spelling is also in the scans, I seem to have changed it by mistake.

To fix the off-by-one issue, I changed the filenames and ids, then I ran build-title, build-manifest, build-spine (and fixed spine order) and build-toc in succession. It is building without any errors. Are there any other changes I need to do that I missed?

**Comment by vr8hub** [comment]
That looks good for the rename!

**Comment by villeporte** [comment]
For the short description, I came up with

> Two flâneurs in Victorian London get caught up with the members of a secret society and their search for a rare Roman coin.

 or 

> Two flâneurs in Victorian London get caught up with the members of a secret society looking for a rare Roman coin.

The sentence you suggested would not strictly be true, since the two idlers are not directly involved with the search and do not know the importance of the coin. I'm open to more suggestions/comments though, it really is not easy to summarize the plot of this book!

(The plot is roughly like this - two idlers in London are walking around and pick up a coin dropped by a fleeing spectacled man - they keep meeting three persons, every time in a different disguise who recount stories which drop small hints about the overall plot - they are all in a secret society and are looking for the spectacled man who regrets working with them and runs away with an important coin)

For the second paragraph of the long description, I was thinking of

> This novel is a Gothic horror classic, and takes the form of an episodic novel, with each chapter containing a story recounted by one of the three impostors, who will stop at nothing to find a certain spectacled man and the Gold Tiberius coin he holds. Among others, it contains “Novel of the Black Seal” and “Novel of the White Powder,” which have been widely anthologized.

**Comment by vr8hub** [comment]
No problem, my example was just that, it wasn't meant to be accurate, since I haven't read it. :) Either of yours works.

For the rest, what you have above (The plot is roughly like this…) is great, maybe fleshed out a little and without reference to "overall plot". That gives us an idea of what the book is about.

What you have as the second paragraph now becomes the third paragraph, and doesn't need "who will stop at nothing… he holds", since that was covered in the second paragraph.

Thus, the second paragraph tells us the plot, i.e. what the novel is about, and the third paragraph tells us about the novel's impact and/or importance.

**Comment by villeporte** [comment]
I've changed the long description using your suggestions.
